services:
  ani-cleaner:
    build:
      context: .
      target: prod
    container_name: ani-cleaner
    volumes:
      - /mnt/media:/mnt/media
    env_file:
      - .env
    restart: unless-stopped